name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  buildnpush:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Login
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the docker image
      run: docker build -t jawad02/first-app:latest .

    - name: Tag the image
      run: docker tag jawad02/first-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/first-app:latest

    - name: Push the image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/first-app:latest
